### ISSUE TITLE
Running (Polymer) tests directly from the browser

### ISSUE THREAD

**Issue by eee-c** [dart-lang/test#115]
I cannot run my Polymer tests from Dartium by navigating to `http://localhost:8081/`. Maybe this is as-designed, but it feels like something that ought to work. The same tests work from the command-line using either Dartium or content_shell with and without `pub serve`. In case it's relevant, my tests are at: https://github.com/eee-c/test-polymer-dart.

I get no test output and see the following error in the console:

```
 Exception: Uncaught Error: FormatException: Unexpected end of input (at character 1)

^

Stack Trace:
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1322)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:472)
#2      _parseJson (dart:convert-patch/convert_patch.dart:20)
#3      JsonDecoder.convert (dart:convert/json.dart:496)
#4      JsonCodec.decode (dart:convert/json.dart:124)
#5      IframeListener.start.<anonymous closure> (package:test/src/runner/browser/iframe_listener.dart:63:26)
#6      _RootZone.runUnary (dart:async/zone.dart:1155)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#9      _Future._completeWithValue (dart:async/future_impl.dart:368)
#10     Future.wait.<anonymous closure> (dart:async/future.dart:299)
#11     _rootRunUnary (dart:async/zone.dart:902)
#12     _CustomZone.runUnary (dart:async/zone.dart:804)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#15     _Future._completeWithValue (dart:async/future_impl.dart:368)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#17     _rootRun (dart:async/zone.dart:895)
#18     _CustomZone.run (dart:async/zone.dart:796)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:731)
#20     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#21     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#22     _ScheduleImmediateHelper._handleMutation (dart:html:42407)
```

Using `Dart VM version: 1.10.0 (Fri Apr 24 04:00:49 2015) on "linux_x64"` with:

```
  test:
    description: test
    source: hosted
    version: "0.12.1"
```

**Comment by zoechi** [comment]
Currently you need to manually replace the x-link-dart with a regular <script type='aplication/dart'... > to make this work.

**Comment by eee-c** [comment]
Thank you! That was driving me nuts.

After replacing:

```html
  <link rel="x-dart-test" href="simple_test.dart">
```

With:

```html
  <script type="application/dart" src="simple_test.dart"></script>
```

I can run the tests directly in Dartium. Of course, it would be even nicer if this worked without changing it :grinning:

**Comment by nex3** [comment]
The test runner doesn't support manually invoking the browser in any way. Once we add a better way to debug browser tests, it will be disabled entirely, and for now we're not going to provide any extra support for it.
