### ISSUE TITLE
Chrome code coverage fails on Windows

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/test#1208]
Running the tests is fine using `test` but when `--coverage` flag is added the following stack trace is generated. The output directory is created but nothing ends up in it.

This is on `2.8.0-dev.17.0 (dev)` with latest test.

```
This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
Unhandled exception:
Invalid argument(s): Illegal character in path
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1732:11)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1796:7)
#2      new _Uri.file (dart:core/uri.dart:1700:11)
#3      Chrome._sourceUriProvider (package:test/src/runner/browser/chrome.dart:131:15)
#4      parseChromeCoverage (package:coverage/src/chrome.dart:59:44)
<asynchronous suspension>
#5      Chrome.gatherCoverage (package:test/src/runner/browser/chrome.dart:109:26)
<asynchronous suspension>
#6      BrowserManager.load.<anonymous closure>.<anonymous closure> (package:test/src/runner/browser/browser_manager.dart:247:49)
#7      RunnerSuite.gatherCoverage (package:test_core/src/runner/runner_suite.dart:85:43)
#8      writeCoverage (package:test_core/src/runner/coverage.dart:16:51)
#9      Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:275:40)
<asynchronous suspension>
#10     Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart)
#11     Engine.run.<anonymous closure> (package:test_core/src/runner/engine.dart:279:8)
#12     _rootRunUnary (dart:async/zone.dart:1155:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#16     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#17     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#18     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#19     _rootRun (dart:async/zone.dart:1147:13)
#20     _CustomZone.run (dart:async/zone.dart:1040:19)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:966:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by grouma** [comment]
I'm unable to reproduce this issue on:
`Dart VM version: 2.8.0-dev.18.0 (dev) (Fri Mar 27 11:10:52 2020 +0100) on "windows_x64"`

What value are you passing to `--coverage`?  I'm doing a simple `pub run test --coverage=.`


I'm using `package:test` version `1.14.2` and `package:coverage` version `0.13.9`. Can you try running `pub upgrade`?

**Comment by natebosch** [comment]
It looks like somehow we end up with a `sourceUrl` or `script` URL that has a character in it's path that isn't an allowed character in a windows file path. Maybe `:` or something?

Do you have any file paths that have unusual characters in them? We should consider adding a `try/catch` so we can print out the specific path that failed.
