### ISSUE TITLE
top-level `expect` throws nSM when not using runner

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/test#132]
EDIT: see comment https://github.com/dart-lang/test/issues/132#issuecomment-107691756, this only affects top-level `expect` statements.

running
```dart
// @TestOn('vm') doesn't seem to make a difference
import 'package:test/test.dart';
main() {
  expect(true, true);
}
```
results in
```
$ dart test.dart
Unhandled exception:
The null object does not have a getter 'closed'.

NoSuchMethodError: method not found: 'closed'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      expect (package:test/src/frontend/expect.dart:42:23)
#3      main (file:///Users/jmesserly/scratch/test.dart:3:9)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:255)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
```
Seems to happen in 0.12.2 as well as master.

According to docs:

> It's also possible to run a test on the Dart VM only by invoking it using dart path/to/test.dart, but this doesn't load the full test runner and will be missing some features.

Context: I'm trying to migrate some existing code from unittest, and easiest thing to do was to leave our various scripts running the test files directly. That was also a really nice way to debug tests by launching them from WebStorm. Not sure if/how the debugger can attach to "pub run test". At first glance I wasn't sure what the workaround would be, as it doesn't look like I can create an Invoker or a runner environment without depending on "src" (don't worry, I won't do that :) ). So at the moment I'm stuck on older unittest.

**Comment by jmesserly** [comment]
Aha, naturally as soon as I file this I figure out what's going on. So it seems we have some code that runs `expect` outside of a test. If it was inside a `test` I'm pretty sure it would work, as _globalDeclarer/LocalTest sets things up correctly. Anyway, that's easy, I can totally fix our code to not do that (I'm not even sure why it is ... but that's another story).

It might be good to support top-level expect (or at least not NoSuchMethodError) but *way* lower priority
