### ISSUE TITLE
Incorrect JS type declarations for callbacks cause difficult-to-debug errors

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#1490]
When writing JS interop code, it's common to get the type declarations subtly wrong. This is especially true in the NNBD world, since JS APIs are not always great at explaining when a value will or will not be null. It would be great if the test framework made it easier to debug these errors, but in practice it obscures them. Take the following example:

```dart
import 'dart:async';

import 'package:js/js.dart';
import 'package:test/test.dart';

@JS('setTimeout')
external setTimeoutWrongType(void Function(Object arg) callback, int ms);

void main() {
  test("test", () {
    setTimeoutWrongType(
        allowInterop(Zone.current.bindUnaryCallbackGuarded(expectAsync1((arg) {
      print("hello!");
    }))), 0);
  });
}
```

This test is broken—it declares that `setTimeout()` passes an argument to its callback, when in fact it does not. I'd expect to see some sort of type error pointing to the relevant line of my test. Instead, when running against Chrome this test times out and when running against Node it produces the following incomprehensible error and then fails to run any further test cases:

<details>
<summary>Error message</summary>

```
00:00 +0: compiling test.dart
Hint: When run on the command-line, the compiled output might require a preamble file located in:
  <sdk>/lib/_internal/js_runtime/lib/preambles.
Compiled 6,133,032 characters Dart to 1,092,367 characters JavaScript in 8.84 seconds
Dart file /tmp/dart_test_IVFLVR/runInBrowser.dart compiled to JavaScript: /tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js

00:00 +0: test
00:00 +0: compiling test.dart
/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:17427
      throw H.wrapException(P.NoSuchMethodError$(this, invocation.get$memberName(), invocation.get$positionalArguments(), invocation.get$namedArguments()));
      ^

NoSuchMethodError: method not found: 'call'
Receiver: Closure '_CustomZone_bindUnaryCallbackGuarded_closure'
Arguments: []
    at Object.wrapException (/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:1059:17)
    at _CustomZone_bindUnaryCallbackGuarded_closure.noSuchMethod$1 (/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:17427:15)
    at Object.noSuchMethod$1$ (/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:3968:42)
    at Object.Primitives_functionNoSuchMethod (/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:934:16)
    at Object.Primitives__genericApplyFunction2 (/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:975:18)
    at Object.Primitives_applyFunction (/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:967:16)
    at Object.Function_apply (/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:5820:16)
    at _callDartFunctionFast (/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:7523:16)
    at Timeout._onTimeout (/tmp/dart_test_YWVTSV/test_NGMTZK/test.dart.node_test.dart.js:7514:18)
    at listOnTimeout (internal/timers.js:554:17) {
  dartException: NoSuchMethodError {
    '_core$_receiver': <ref *8> _CustomZone_bindUnaryCallbackGuarded_closure {
      '$this': _CustomZone {
        _run: _RunNullaryZoneFunction {
          zone: _RootZone {},
          '$function': StaticClosure {
            '$initialize': [Function: StaticClosure],
            constructor: [Function: static_tear_off],
            '$static_name': '_rootRun',
            '$signature': [Function (anonymous)],
            'call$1$4': [Function],
            'call$4': [Function],
            'call*': [Function],
            '$requiredArgCount': 4,
            '$defaultValues': null
          }
        },
        _runUnary: _RunUnaryZoneFunction {
          zone: _RootZone {},
          '$function': StaticClosure {
            '$initialize': [Function: StaticClosure],
            constructor: [Function: static_tear_off],
            '$static_name': '_rootRunUnary',
            '$signature': [Function (anonymous)],
            'call$2$5': [Function],
            'call$5': [Function],
            'call*': [Function],
            '$requiredArgCount': 5,
            '$defaultValues': null
          }
        },
        _runBinary: _RunBinaryZoneFunction {
          zone: _RootZone {},
          '$function': StaticClosure {
            '$initialize': [Function: StaticClosure],
            constructor: [Function: static_tear_off],
            '$static_name': '_rootRunBinary',
            '$signature': [Function (anonymous)],
            'call$3$6': [Function],
            'call$6': [Function],
            'call*': [Function],
            '$requiredArgCount': 6,
            '$defaultValues': null
          }
        },
        _registerCallback: <ref *1> _RegisterNullaryZoneFunction {
          zone: _CustomZone {
            _run: [_RunNullaryZoneFunction],
            _runUnary: [_RunUnaryZoneFunction],
            _runBinary: [_RunBinaryZoneFunction],
            _registerCallback: [Circular *1],
            _registerUnaryCallback: [_RegisterUnaryZoneFunction],
            _registerBinaryCallback: [_RegisterBinaryZoneFunction],
            _errorCallback: [_ZoneFunction],
            _scheduleMicrotask: [_ZoneFunction],
            _createTimer: [_ZoneFunction],
            _createPeriodicTimer: [_ZoneFunction],
            _print: [_ZoneFunction],
            _fork: [_ZoneFunction],
            _handleUncaughtError: [_ZoneFunction],
            _delegateCache: null,
            parent: [_CustomZone],
            '_async$_map': [_HashMap]
          },
          '$function': anonymous {
            _self: [StackZoneSpecification],
            _target: [Function],
            _receiver: null,
            _name: '_stack_zone_specification$_registerCallback$1$4'
          }
        },
        _registerUnaryCallback: <ref *2> _RegisterUnaryZoneFunction {
          zone: _CustomZone {
            _run: [_RunNullaryZoneFunction],
            _runUnary: [_RunUnaryZoneFunction],
            _runBinary: [_RunBinaryZoneFunction],
            _registerCallback: [_RegisterNullaryZoneFunction],
            _registerUnaryCallback: [Circular *2],
            _registerBinaryCallback: [_RegisterBinaryZoneFunction],
            _errorCallback: [_ZoneFunction],
            _scheduleMicrotask: [_ZoneFunction],
            _createTimer: [_ZoneFunction],
            _createPeriodicTimer: [_ZoneFunction],
            _print: [_ZoneFunction],
            _fork: [_ZoneFunction],
            _handleUncaughtError: [_ZoneFunction],
            _delegateCache: null,
            parent: [_CustomZone],
            '_async$_map': [_HashMap]
          },
          '$function': anonymous {
            _self: [StackZoneSpecification],
            _target: [Function],
            _receiver: null,
            _name: '_stack_zone_specification$_registerUnaryCallback$2$4'
          }
        },
        _registerBinaryCallback: <ref *3> _RegisterBinaryZoneFunction {
          zone: _CustomZone {
            _run: [_RunNullaryZoneFunction],
            _runUnary: [_RunUnaryZoneFunction],
            _runBinary: [_RunBinaryZoneFunction],
            _registerCallback: [_RegisterNullaryZoneFunction],
            _registerUnaryCallback: [_RegisterUnaryZoneFunction],
            _registerBinaryCallback: [Circular *3],
            _errorCallback: [_ZoneFunction],
            _scheduleMicrotask: [_ZoneFunction],
            _createTimer: [_ZoneFunction],
            _createPeriodicTimer: [_ZoneFunction],
            _print: [_ZoneFunction],
            _fork: [_ZoneFunction],
            _handleUncaughtError: [_ZoneFunction],
            _delegateCache: null,
            parent: [_CustomZone],
            '_async$_map': [_HashMap]
          },
          '$function': anonymous {
            _self: [StackZoneSpecification],
            _target: [Function],
            _receiver: null,
            _name: '_stack_zone_specification$_registerBinaryCallback$3$4'
          }
        },
        _errorCallback: <ref *4> _ZoneFunction {
          zone: _CustomZone {
            _run: [_RunNullaryZoneFunction],
            _runUnary: [_RunUnaryZoneFunction],
            _runBinary: [_RunBinaryZoneFunction],
            _registerCallback: [_RegisterNullaryZoneFunction],
            _registerUnaryCallback: [_RegisterUnaryZoneFunction],
            _registerBinaryCallback: [_RegisterBinaryZoneFunction],
            _errorCallback: [Circular *4],
            _scheduleMicrotask: [_ZoneFunction],
            _createTimer: [_ZoneFunction],
            _createPeriodicTimer: [_ZoneFunction],
            _print: [_ZoneFunction],
            _fork: [_ZoneFunction],
            _handleUncaughtError: [_ZoneFunction],
            _delegateCache: null,
            parent: [_CustomZone],
            '_async$_map': [_HashMap]
          },
          '$function': anonymous {
            _self: [StackZoneSpecification],
            _target: [Function],
            _receiver: null,
            _name: '_stack_zone_specification$_errorCallback$5'
          },
          '$ti': Rti {
            _as: [Function: _generalAsCheckImplementation],
            _is: [Function: _generalIsTestImplementation],
            _precomputed1: [Rti],
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: '_ZoneFunction',
            _rest: [Array],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '_ZoneFunction<AsyncError?(Zone,ZoneDelegate,Zone,Object,StackTrace?)>'
          }
        },
        _scheduleMicrotask: _ZoneFunction {
          zone: _RootZone {},
          '$function': StaticClosure {
            '$initialize': [Function: StaticClosure],
            constructor: [Function: static_tear_off],
            '$static_name': '_rootScheduleMicrotask',
            '$signature': [Function (anonymous)],
            'call$4': [Function],
            'call*': [Function],
            '$requiredArgCount': 4,
            '$defaultValues': null
          },
          '$ti': Rti {
            _as: [Function: _installSpecializedAsCheck],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: [Rti],
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: '_ZoneFunction',
            _rest: [Array],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '_ZoneFunction<~(Zone,ZoneDelegate,Zone,~())>'
          }
        },
        _createTimer: _ZoneFunction {
          zone: _RootZone {},
          '$function': StaticClosure {
            '$initialize': [Function: StaticClosure],
            constructor: [Function: static_tear_off],
            '$static_name': '_rootCreateTimer',
            '$signature': [Function (anonymous)],
            'call$5': [Function],
            'call*': [Function],
            '$requiredArgCount': 5,
            '$defaultValues': null
          },
          '$ti': Rti {
            _as: [Function: _installSpecializedAsCheck],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: [Rti],
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: '_ZoneFunction',
            _rest: [Array],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '_ZoneFunction<Timer(Zone,ZoneDelegate,Zone,Duration,~())>'
          }
        },
        _createPeriodicTimer: _ZoneFunction {
          zone: _RootZone {},
          '$function': StaticClosure {
            '$initialize': [Function: StaticClosure],
            constructor: [Function: static_tear_off],
            '$static_name': '_rootCreatePeriodicTimer',
            '$signature': [Function (anonymous)],
            'call$5': [Function],
            'call*': [Function],
            '$requiredArgCount': 5,
            '$defaultValues': null
          },
          '$ti': Rti {
            _as: [Function: _installSpecializedAsCheck],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: [Rti],
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: '_ZoneFunction',
            _rest: [Array],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '_ZoneFunction<Timer(Zone,ZoneDelegate,Zone,Duration,~(Timer))>'
          }
        },
        _print: <ref *5> _ZoneFunction {
          zone: _CustomZone {
            _run: [_RunNullaryZoneFunction],
            _runUnary: [_RunUnaryZoneFunction],
            _runBinary: [_RunBinaryZoneFunction],
            _registerCallback: [_RegisterNullaryZoneFunction],
            _registerUnaryCallback: [_RegisterUnaryZoneFunction],
            _registerBinaryCallback: [_RegisterBinaryZoneFunction],
            _errorCallback: [_ZoneFunction],
            _scheduleMicrotask: [_ZoneFunction],
            _createTimer: [_ZoneFunction],
            _createPeriodicTimer: [_ZoneFunction],
            _print: [Circular *5],
            _fork: [_ZoneFunction],
            _handleUncaughtError: [_ZoneFunction],
            _delegateCache: null,
            parent: [_CustomZone],
            '_async$_map': [_HashMap]
          },
          '$function': Invoker__onRun___closure0 { '$this': [Invoker] },
          '$ti': Rti {
            _as: [Function: _generalAsCheckImplementation],
            _is: [Function: _generalIsTestImplementation],
            _precomputed1: [Rti],
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: '_ZoneFunction',
            _rest: [Array],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '_ZoneFunction<~(Zone,ZoneDelegate,Zone,String)>'
          }
        },
        _fork: _ZoneFunction {
          zone: _RootZone {},
          '$function': StaticClosure {
            '$initialize': [Function: StaticClosure],
            constructor: [Function: static_tear_off],
            '$static_name': '_rootFork',
            '$signature': [Function (anonymous)],
            'call$5': [Function],
            'call*': [Function],
            '$requiredArgCount': 5,
            '$defaultValues': null
          },
          '$ti': Rti {
            _as: [Function: _installSpecializedAsCheck],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: [Rti],
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: '_ZoneFunction',
            _rest: [Array],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '_ZoneFunction<Zone(Zone,ZoneDelegate,Zone,ZoneSpecification?,Map<Object?,Object?>?)>'
          }
        },
        _handleUncaughtError: <ref *6> _ZoneFunction {
          zone: _CustomZone {
            _run: [_RunNullaryZoneFunction],
            _runUnary: [_RunUnaryZoneFunction],
            _runBinary: [_RunBinaryZoneFunction],
            _registerCallback: [_RegisterNullaryZoneFunction],
            _registerUnaryCallback: [_RegisterUnaryZoneFunction],
            _registerBinaryCallback: [_RegisterBinaryZoneFunction],
            _errorCallback: [_ZoneFunction],
            _scheduleMicrotask: [_ZoneFunction],
            _createTimer: [_ZoneFunction],
            _createPeriodicTimer: [_ZoneFunction],
            _print: [_ZoneFunction],
            _fork: [_ZoneFunction],
            _handleUncaughtError: [Circular *6],
            _delegateCache: null,
            parent: [_CustomZone],
            '_async$_map': [_HashMap]
          },
          '$function': Invoker_guard_closure {},
          '$ti': Rti {
            _as: [Function: _generalAsCheckImplementation],
            _is: [Function: _generalIsTestImplementation],
            _precomputed1: [Rti],
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: '_ZoneFunction',
            _rest: [Array],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '_ZoneFunction<~(Zone,ZoneDelegate,Zone,Object,StackTrace)>'
          }
        },
        _delegateCache: null,
        parent: _CustomZone {
          _run: _RunNullaryZoneFunction {
            zone: _RootZone {},
            '$function': [StaticClosure]
          },
          _runUnary: _RunUnaryZoneFunction {
            zone: _RootZone {},
            '$function': [StaticClosure]
          },
          _runBinary: _RunBinaryZoneFunction {
            zone: _RootZone {},
            '$function': [StaticClosure]
          },
          _registerCallback: <ref *1> _RegisterNullaryZoneFunction {
            zone: [_CustomZone],
            '$function': [anonymous]
          },
          _registerUnaryCallback: <ref *2> _RegisterUnaryZoneFunction {
            zone: [_CustomZone],
            '$function': [anonymous]
          },
          _registerBinaryCallback: <ref *3> _RegisterBinaryZoneFunction {
            zone: [_CustomZone],
            '$function': [anonymous]
          },
          _errorCallback: <ref *4> _ZoneFunction {
            zone: [_CustomZone],
            '$function': [anonymous],
            '$ti': [Rti]
          },
          _scheduleMicrotask: _ZoneFunction {
            zone: _RootZone {},
            '$function': [StaticClosure],
            '$ti': [Rti]
          },
          _createTimer: _ZoneFunction {
            zone: _RootZone {},
            '$function': [StaticClosure],
            '$ti': [Rti]
          },
          _createPeriodicTimer: _ZoneFunction {
            zone: _RootZone {},
            '$function': [StaticClosure],
            '$ti': [Rti]
          },
          _print: <ref *5> _ZoneFunction {
            zone: [_CustomZone],
            '$function': [Invoker__onRun___closure0],
            '$ti': [Rti]
          },
          _fork: _ZoneFunction {
            zone: _RootZone {},
            '$function': [StaticClosure],
            '$ti': [Rti]
          },
          _handleUncaughtError: <ref *6> _ZoneFunction {
            zone: [_CustomZone],
            '$function': Invoker_guard_closure {},
            '$ti': [Rti]
          },
          _delegateCache: null,
          parent: _CustomZone {
            _run: [_RunNullaryZoneFunction],
            _runUnary: [_RunUnaryZoneFunction],
            _runBinary: [_RunBinaryZoneFunction],
            _registerCallback: [_RegisterNullaryZoneFunction],
            _registerUnaryCallback: [_RegisterUnaryZoneFunction],
            _registerBinaryCallback: [_RegisterBinaryZoneFunction],
            _errorCallback: [_ZoneFunction],
            _scheduleMicrotask: [_ZoneFunction],
            _createTimer: [_ZoneFunction],
            _createPeriodicTimer: [_ZoneFunction],
            _print: [_ZoneFunction],
            _fork: [_ZoneFunction],
            _handleUncaughtError: [_ZoneFunction],
            _delegateCache: null,
            parent: [_CustomZone],
            '_async$_map': [_HashMap]
          },
          '_async$_map': _HashMap {
            '_collection$_length': 4,
            '_collection$_strings': null,
            '_collection$_nums': null,
            '_collection$_rest': [Object: null prototype],
            '_collection$_keys': null,
            '$ti': [Rti]
          }
        },
        '_async$_map': _HashMap {
          '_collection$_length': 5,
          '_collection$_strings': null,
          '_collection$_nums': null,
          '_collection$_rest': [Object: null prototype] {
            '163058210': [Array],
            '175058077': [Array],
            '245597179': [Array],
            '798670612': [Array],
            '869760555': [Array]
          },
          '_collection$_keys': null,
          '$ti': Rti {
            _as: [Function: _installSpecializedAsCheck],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: [Rti],
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: '_HashMap',
            _rest: [Array],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '_HashMap<Object?,Object?>'
          }
        }
      },
      registered: StackZoneSpecification__registerUnaryCallback_closure {
        '$this': StackZoneSpecification {
          _chains: Expando {
            _jsWeakMapOrKey: [WeakMap],
            name: 'stack chains',
            '$ti': [Rti]
          },
          '_stack_zone_specification$_onError': null,
          _currentNode: null,
          _errorZone: false
        },
        f: anonymous {
          _self: _ExpectedFunction {
            '_expect_async$_callback': main__closure {},
            _minExpectedCalls: 1,
            _maxExpectedCalls: 1,
            _id: '',
            _reason: '',
            _actualCalls: 0,
            '_expect_async$_zone': [_CustomZone],
            ___ExpectedFunction__complete: false,
            '$ti': [Rti]
          },
          _target: [Function: max1$1] {
            '$callName': 'call$1',
            '$requiredArgCount': 0,
            '$defaultValues': [Function (anonymous)],
            '$stubName': 'max1$1'
          },
          _receiver: null,
          _name: 'max1$1'
        },
        node: _Node {
          trace: LazyTrace {
            '_lazy_trace$_thunk': [StackZoneSpecification__currentTrace_closure],
            __LazyTrace__trace: null
          },
          previous: _Node { trace: [LazyTrace], previous: [_Node] }
        },
        T: Rti {
          _as: [Function: _asObject],
          _is: [Function: _installSpecializedIsTest],
          _precomputed1: null,
          _specializedTestResource: null,
          _cachedRuntimeType: null,
          _kind: 9,
          _primary: 'Object',
          _rest: [],
          _evalCache: Map(1) { '~(0)' => [Rti] },
          _bindCache: null,
          _canonicalRecipe: 'Object'
        },
        R: <ref *7> Rti {
          _as: [Function: _asTop],
          _is: [Function: _installSpecializedIsTest],
          _precomputed1: null,
          _specializedTestResource: null,
          _cachedRuntimeType: null,
          _kind: 3,
          _primary: null,
          _rest: null,
          _evalCache: Map(5) {
            '@<0>' => [Rti],
            '0()' => [Rti],
            '_Future<0>' => [Rti],
            '0?' => [Circular *7],
            '0/' => [Circular *7]
          },
          _bindCache: null,
          _canonicalRecipe: '~'
        }
      },
      T: Rti {
        _as: [Function: _asObject],
        _is: [Function: _installSpecializedIsTest],
        _precomputed1: null,
        _specializedTestResource: null,
        _cachedRuntimeType: null,
        _kind: 9,
        _primary: 'Object',
        _rest: [],
        _evalCache: Map(1) {
          '~(0)' => Rti {
            _as: [Function: _generalAsCheckImplementation],
            _is: [Function: _generalIsTestImplementation],
            _precomputed1: null,
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 11,
            _primary: [Rti],
            _rest: [_FunctionParameters],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '~(Object)'
          }
        },
        _bindCache: null,
        _canonicalRecipe: 'Object'
      },
      '$dart_jsFunction': [Function (anonymous)] {
        '___dart__$dart_dartClosure_ZxYxX_0_': [Circular *8]
      }
    },
    '_core$_memberName': Symbol { '__internal$_name': 'call' },
    '_core$_arguments': [
      'immutable$list': [Function: Array],
      'fixed$length': [Function: Array],
      [Symbol($ti)]: Rti {
        _as: [Function: _generalAsCheckImplementation],
        _is: [Function: _isTestViaProperty],
        _precomputed1: Rti {
          _as: [Function: _asTop],
          _is: [Function: _installSpecializedIsTest],
          _precomputed1: null,
          _specializedTestResource: null,
          _cachedRuntimeType: null,
          _kind: 2,
          _primary: null,
          _rest: null,
          _evalCache: Map(4) {
            '@<0>' => [Rti],
            '_Future<0>' => [Rti],
            '0()' => [Rti],
            '_AsyncAwaitCompleter<0>' => [Rti]
          },
          _bindCache: null,
          _canonicalRecipe: '@'
        },
        _specializedTestResource: '$isJSArray',
        _cachedRuntimeType: null,
        _kind: 9,
        _primary: 'JSArray',
        _rest: [
          Rti {
            _as: [Function: _asTop],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: null,
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 2,
            _primary: null,
            _rest: null,
            _evalCache: [Map],
            _bindCache: null,
            _canonicalRecipe: '@'
          }
        ],
        _evalCache: Map(2) {
          'ArrayIterator<1>' => Rti {
            _as: [Function: _installSpecializedAsCheck],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: [Rti],
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: 'ArrayIterator',
            _rest: [Array],
            _evalCache: [Map],
            _bindCache: null,
            _canonicalRecipe: 'ArrayIterator<@>'
          },
          'Iterable<1>' => Rti {
            _as: [Function: _generalAsCheckImplementation],
            _is: [Function: _isTestViaProperty],
            _precomputed1: [Rti],
            _specializedTestResource: '$isIterable',
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: 'Iterable',
            _rest: [Array],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: 'Iterable<@>'
          }
        },
        _bindCache: null,
        _canonicalRecipe: 'JSArray<@>'
      }
    ],
    _namedArguments: ConstantStringMap {
      '__js_helper$_length': 0,
      _jsObject: {},
      _keys: [
        'immutable$list': [Function: Array],
        'fixed$length': [Function: Array],
        [Symbol($ti)]: Rti {
          _as: [Function: _installSpecializedAsCheck],
          _is: [Function: _installSpecializedIsTest],
          _precomputed1: Rti {
            _as: [Function: _installSpecializedAsCheck],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: null,
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: 'Symbol0',
            _rest: [],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: 'Symbol0'
          },
          _specializedTestResource: null,
          _cachedRuntimeType: null,
          _kind: 9,
          _primary: 'JSArray',
          _rest: [ [Rti] ],
          _evalCache: null,
          _bindCache: null,
          _canonicalRecipe: 'JSArray<Symbol0>'
        }
      ],
      '$ti': Rti {
        _as: [Function: _installSpecializedAsCheck],
        _is: [Function: _installSpecializedIsTest],
        _precomputed1: Rti {
          _as: [Function: _installSpecializedAsCheck],
          _is: [Function: _installSpecializedIsTest],
          _precomputed1: null,
          _specializedTestResource: null,
          _cachedRuntimeType: null,
          _kind: 9,
          _primary: 'Symbol0',
          _rest: [],
          _evalCache: null,
          _bindCache: null,
          _canonicalRecipe: 'Symbol0'
        },
        _specializedTestResource: null,
        _cachedRuntimeType: null,
        _kind: 9,
        _primary: 'ConstantStringMap',
        _rest: [
          Rti {
            _as: [Function: _installSpecializedAsCheck],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: null,
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 9,
            _primary: 'Symbol0',
            _rest: [],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: 'Symbol0'
          },
          Rti {
            _as: [Function: _asTop],
            _is: [Function: _installSpecializedIsTest],
            _precomputed1: null,
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 2,
            _primary: null,
            _rest: null,
            _evalCache: [Map],
            _bindCache: null,
            _canonicalRecipe: '@'
          }
        ],
        _evalCache: Map(1) {
          '~(1,2)' => Rti {
            _as: [Function: _generalAsCheckImplementation],
            _is: [Function: _generalIsTestImplementation],
            _precomputed1: null,
            _specializedTestResource: null,
            _cachedRuntimeType: null,
            _kind: 11,
            _primary: [Rti],
            _rest: [_FunctionParameters],
            _evalCache: null,
            _bindCache: null,
            _canonicalRecipe: '~(Symbol0,@)'
          }
        },
        _bindCache: null,
        _canonicalRecipe: 'ConstantStringMap<Symbol0,@>'
      }
    }
  }
}
00:00 +0: test - did not complete [E]
00:00 +0: Some tests failed.
```

</details>

**Comment by natebosch** [comment]
This issue seems primarily about `package:js` UX when the JS side fails to call in to a callback.

Since this doesn't happen synchronously or in any Dart zone I don't think we have any options on our side to surface the error. We could maybe look at a feature where browser console errors are forwarded through but that's likely to be a large amount of effort.

@sigmundch @srujzs - is there anything we could look at on the compiler side to surface these errors in Dart somehow?

**Comment by srujzs** [comment]
This would partly involve checking types at the `external` declaration boundary right? I think because of the way we implement JS types with interceptors, this won't work. I also don't see anything we can do with `allowInterop` that could add checks here but I'm unsure.

Chrome timing out is confusing and unexpected. The Node error is interesting however and seems like a bug in how we're wrapping and then calling interop functions when it comes to Zones in dart2js.

**Comment by natebosch** [comment]
I wonder if it would be feasible and sensible for `allowInterop` to hold on to the `Zone` where it was called, and when it gets invoked to run the Dart callback in that zone.

I think the main problem is that the error just bubbles up to JS - there is no way to catch it in Dart.

**Comment by natebosch** [comment]
@sigmundch @srujzs - any thoughts on on running `allowInterop` callbacks in a Dart zone?

I don't think there is much we can do about this on the `test` side, since I think we lose any ability to intercept this exception.

**Comment by sigmundch** [comment]
cc @joshualitt as well.

@natebosch - could you clarify what you mean by running callbacks in the zone? In particular, the example above was with a callback wrapped in a zone already. Or is the problem here the trampoline logic introduced by allowInterop? (and we'd like that logic itself to be in a Dart zone?)

As for how to detect this better going forward. We are making progress on an effort to expose JSTypes explicitly and enforce that all interop APIs must use a JSType and not a Dart type. We intend to have a migration plan and a way to make this kind of change less disruptive, but eventually the idea is to disallow mixing the types as much. A dart signature on a JS callback would no longer be allowed, for example.

That said, so far we are working with one type for all JSFunctions, so it doesn't quite help detect discrepancies in the signature of the callback like the issue above. However, we would start detecting more issues statically, like missing `allowInterop` call.

**Comment by joshualitt** [comment]
RE: the typing discrepancy, even though we will only have one type for all JS functions(`JSFunction`), I think the overall behavior will be much safer with JS types because Dart functions exported to JS must take and return JS types. With respect to the above example, this will do two things:

1. It will be forbidden to return a Dart `Future` from a Dart function passed to the JS types equivalent of `allowInterop`. This is because `Future` is not a JS type. Users will have to convert the Dart `Future` to a `JSPromise` explicitly, and when they do so they will have to handle any potential error cases in Dart.
2. It will also be forbidden for a Dart function exported to JS to take an `Object`. Users will have to take `JSAny`. In this case, if the Dart function expects more arguments than JS supplies, then the behavior will be backend dependent for the time being. On JS backends, this will trigger a null check failure, which will throw, and be caught in the `futureToPromise` logic required by (1). On Wasm backends I think this example will actually work just fine because `JSUndefined <: JSAny`, and AFAICT the argument isn't actually used for anything. Of course, if the user instead uses `JSAny?` then the behavior will be consistent on both backends(`JSUndefined <: JSAny?` on all backends).

So, I think things will be much better here in the near future.

**Comment by joshualitt** [comment]
Whoops, I just realized that `bindUnaryCallbackGuarded` doesn't return a `Future` does it? The `expectAsync` threw me off. How does this code involve asynchronous logic without explicitly involving `Future`s at some point?

I'm not sure we have any good options here unfortunately. I don't think we have a good way of knowing whether or not an arbitrary function passed to `allowInterop` might need to hold onto a zone, so we either do it for all functions passed to `allowInterop`, which seems wasteful, or ask the user to manage this logic, which leads to error prone behavior.

If it's not all that common to work with zones in functions passed to `allowInterop`, then maybe the only reasonable solution is to solve this with better documentation? That said, this behavior is very surprising, and maybe we can find a way to make it safer in the long term.

**Comment by natebosch** [comment]
> The `expectAsync` threw me off. How does this code involve asynchronous logic without explicitly involving `Future`s at some point?

The "async" in `expectAsync` relates to an expectation that something will asynchronously run the callback at some later point.

> @natebosch - could you clarify what you mean by running callbacks in the zone? In particular, the example above was with a callback wrapped in a zone already. Or is the problem here the trampoline logic introduced by allowInterop? (and we'd like that logic itself to be in a Dart zone?)

What would be best is if calls to the function returned by `allowInterop` surface errors in the Dart zone. Taking `test` out of the reproduction, what I'd like is for the error zone's handler to run. Instead I have an exception that I cannot catch and handle in any way from Dart.

```dart
import 'dart:async';

import 'package:js/js.dart';

@JS('setTimeout')
external setTimeoutWrongType(void Function(Object arg) callback, int ms);

void main() {
  runZonedGuarded(() {
    setTimeoutWrongType(
        allowInterop(Zone.current.bindUnaryCallbackGuarded((arg) {})), 0);
                  // ^ this zone wrapping has no chance to have an effect
  }, (error, stackTrace) {
    print('Error: $error'); // Ideally this error handler should work.
  });
}
```

> I'm not sure we have any good options here unfortunately. I don't think we have a good way of knowing whether or not an arbitrary function passed to `allowInterop` might need to hold onto a zone, so we either do it for all functions passed to `allowInterop`, which seems wasteful, or ask the user to manage this logic, which leads to error prone behavior.

I can see an argument for doing the zone wrapping for users in all cases so that users get Dart-like error zone semantics without needing to bind the callback manually like in this example.

If we fix the signature issue so that the callback works, but have an error in Dart, it would be reasonable to make the following have equivalent semantics between `setTimeout()` and `Timer()`.

```dart
import 'dart:async';

import 'package:js/js.dart';

@JS('setTimeout')
external setTimeout(void Function() callback, int ms);

void main() {
  runZonedGuarded(() {
    Timer(const Duration(), () {
      throw 'sad';
    });
    // ^ This one can be caught.
    setTimeout(allowInterop(() {
      throw 'sadder';
    }), 0);
    // ^ This one gets lost.
  }, (error, stackTrace) {
    print('Error: $error');
  });
}
```
