### ISSUE TITLE
Exception on time out

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/test#315]
I don't know whether this bug is also in the test package, but I found it while debugging a failing test. Operating at human speed caused the test to time out, producing the exception below.

I was running on my Mac, using a bleeding edge build. The DartDoc for the `request` getter explicitly states that it can return `null`, but the code doesn't check for `null`. (By the way, the DartDoc contains a typo at "has is".)

```
Unhandled exception:
The null object does not have a method 'toUpperCase'.

NoSuchMethodError: method not found: 'toUpperCase'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SimpleConfiguration.formatResult (package:unittest/src/simple_configuration.dart:142:34)
#3      SimpleConfiguration.onSummary (package:unittest/src/simple_configuration.dart:171:13)
#4      _completeTests (package:unittest/unittest.dart:366:10)
#5      _runTest (package:unittest/unittest.dart:308:5)
#6      _nextTestCase (package:unittest/unittest.dart:256:3)
#7      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by nex3** [comment]
It looks like this is an issue with `unittest` 0.11.x, which is no longer officially supported. I bet if you upgrade to 0.12.x, this'll go away.
