### ISSUE TITLE
malformed type 'DelegateingSink' is not loaded

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#323]
Starting today whenever I run a test like

**test/my_test.dart**
```dart
import 'package:test/test.dart';

main() {
  group('xx', () {
    test('yy', () {
    });
  });
}
```

with `dart test/my_test.dart` or `pub run test test/my_test.dart`
I get this error 

```
/usr/local/apps/dart/dart-sdk/bin/dart --ignore-unrecognized-flags --checked --debug:57845 --break-at-isolate-spawn --enable-vm-service:42986 --trace_service_pause_events /home/zoechi/dart/playground/projects/sdk_constraint/test/my_test.dart
Observatory listening on http://127.0.0.1:42986
Unhandled exception:
Uncaught Error: 'package:test/src/runner/engine.dart': malformed type: line 95 pos 36: type 'DelegatingSink' is not loaded
  Sink<Suite> get suiteSink => new DelegatingSink(_suiteController.sink);
                                   ^
type error.
Stack Trace:
#0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:58)
#1      Engine.suiteSink (package:test/src/runner/engine.dart:95:36)
#2      _declarer.<anonymous closure>.<<anonymous closure>_async_body> (package:test/test.dart:60:12)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#5      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:894)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Process finished with exit code 255
```

After quite some investigation I found out that this was caused by upgrading the test package. 
I went back from 0.12.3+9 to 0.12.3+1 and running tests starts working again. 
So the issue is caused by changes from 0.12.3+1 to 0.12.3+7 (where I also get this error)

I already purged all test packages from `~/.pub-cache/hosted` (and run pub upgrade).
I can navigate to the class using the link in the error output and the analyzer doesn't show any errors.  
The project used to reproduce doesn't contain anything except a dependency to `test` (0.12.3+9) and the test shown above.
I reinstalled the newest bleeding edge and tried an older version I had installed last week (1.12.0-edge...), but this also didn't change anything.

**Comment by nex3** [comment]
This is an incompatibility with the latest version of the `async` package that's already been fixed in the latest `test` releases.
