### ISSUE TITLE
async exception now recognized by `throwsA`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#732]
```dart
    test('unauthenticated write access should be prevented', () {
      expect(firebase.set({'foo': 'bar'}), throwsA(PlatformException));
    });
```

where `firebase.set()` is

```dart
Future<Null> set(dynamic value, {dynamic priority}) {
   return _database._channel.invokeMethod(...
```

results in 

```
[   +8 ms] I/flutter ( 3704): 4 2017-12-07 15:40:22.102444 FINE rx.logging_middleware GroupActions-subGroupsChanged: 
[ +821 ms] W/SyncTree( 3704): Listen at /test_1e0f56e8-239a-45c1-9843-aa8bc4aa82b5/subGroup failed: DatabaseError: Permission denied
[   +1 ms] W/SyncTree( 3704): Listen at /test_1e0f56e8-239a-45c1-9843-aa8bc4aa82b5/group failed: DatabaseError: Permission denied
[        ] W/SyncTree( 3704): Listen at /test_1e0f56e8-239a-45c1-9843-aa8bc4aa82b5/joinRequestCreate/jYARomlFLlae55dUAShNWpGzSVk1 failed: DatabaseError: Permission denied
[        ] W/RepoOperation( 3704): setValue at / failed: DatabaseError: Permission denied
[  +70 ms] I/flutter ( 3704): 00:02 [32m+0[0m[31m -1[0m: firebase unauthenticated write access should be prevented [1m[31m[E][0m[0m
[        ] I/flutter ( 3704):   Expected: throws ?:<PlatformException>
[        ] I/flutter ( 3704):     Actual: <Instance of '_Future'>
[        ] I/flutter ( 3704):      Which: threw PlatformException:<PlatformException(-3, Permission denied, )>
[        ] I/flutter ( 3704):             stack package:flutter/src/services/message_codecs.dart 514                                                                      StandardMethodCodec.decodeEnvelope
[        ] I/flutter ( 3704):                   package:flutter/src/services/platform_channel.dart 154                                                                    MethodChannel.invokeMethod
[        ] I/flutter ( 3704):                   ===== asynchronous gap ===========================
[        ] I/flutter ( 3704):                   dart:async                                                                                                                _Completer.completeError
[        ] I/flutter ( 3704):                   package:flutter/src/services/platform_channel.dart                                                                        MethodChannel.invokeMethod
[        ] I/flutter ( 3704):                   ===== asynchronous gap ===========================
[        ] I/flutter ( 3704):                   dart:async                         
[  +18 ms] I/flutter ( 3704):   package:test/src/frontend/expect.dart 164                                                                                 fail
[        ] I/flutter ( 3704):   package:test/src/frontend/expect.dart 141                                                                                 _expect.<fn>
[        ] I/flutter ( 3704):   package:stack_trace/src/stack_zone_specification.dart 129                                                                 StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
[        ] I/flutter ( 3704):   package:stack_trace/src/stack_zone_specification.dart 209                                                                 StackZoneSpecification._run
[        ] I/flutter ( 3704):   package:stack_trace/src/stack_zone_specification.dart 129                                                                 StackZoneSpecification._registerUnaryCallback.<fn>
[        ] I/flutter ( 3704):   dart:async/zone.dart 1134                                                                                                 _rootRunUnary
[        ] I/flutter ( 3704):   dart:async/zone.dart 1031                                                                                     
[   +2 ms] I/flutter ( 3704): 00:02 [32m+0[0m[31m -1[0m: (tearDownAll)[0m
[  +10 ms] I/flutter ( 3704): 00:02 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
[        ] I/flutter ( 3704): 
[   +1 ms] E/flutter ( 3704): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[        ] E/flutter ( 3704): Dummy exception to set exit code.
[        ] E/flutter ( 3704): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
[        ] E/flutter ( 3704): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] E/flutter ( 3704): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[  +44 ms] D/        ( 3704): HostConnection::get() New Host Connection established 0xa7864d00, tid 3728
[  +98 ms] Service protocol connection closed.
```

This test code is in a Flutter drive test and in the file that runs on the device (emulator), not in the `..._test.dart` file.

```
✓] Flutter (on Mac OS X 10.13.1 17B1003, locale en-AT, channel alpha)
    • Flutter at /Users/zoechi/flutter/flutter
    • Framework revision fd7853faad (2 days ago), 2017-12-05 16:12:55 -0800
    • Engine revision b57fca02b5
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d4cfecb1065d322d3670df7e9ec9a0cc2d4b90f0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 19.1
    • Dart plugin version 173.3727.108

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

The used `test` package version is `0.12.26`

**Comment by nex3** [comment]
Right now, your code is checking that the exception is equal to the value `PlatformException`, which is an instance of `Type`. If you want to check that it's an instance of `PlatformException`, you need to use `throwsA(new isInstanceOf<PlatformException>())`.

**Comment by zoechi** [comment]
@nex3 thanks a lot
