### ISSUE TITLE
Exception running coverage in content-shell (Dart 1.24.3)

### ISSUE THREAD

**Issue by travissanderson-wf** [dart-lang/test#781]
fyi @nex3:
We believe the latest release's inclusion of https://github.com/dart-lang/test/pull/779 is breaking CI for us in a number of (maybe all of?) our Dart repos.  Pinning to test `<0.12.32` resolves the issue. We are seeing the following exceptions when attempting to run coverage in content-shell:

```
Uncaught Unhandled exception:
        'dart:io-patch/platform_patch.dart': error: line 12: native function 'Platform_OperatingSystem' (0 arguments) cannot be found
          static String _operatingSystem() native "Platform_OperatingSystem";
          ^

        #0      _Platform.operatingSystem (platform_impl.dart:60)
        #1      Platform._operatingSystem (platform.dart:71)
        #2      Platform._operatingSystem (platform.dart:71)
        #3      Platform.operatingSystem (platform.dart:95)
        #4      currentOS.<anonymous closure> (package:test/src/util/io.dart:46:23)
        #5      currentOS (package:test/src/util/io.dart:51:3)
        #6      currentOS (package:test/src/util/io.dart:45:23)
        #7      currentOSGuess.<anonymous closure> (package:test/src/utils.dart:59:43)
        #8      _ifSupported (package:test/src/utils.dart:97:20)
        #9      currentOSGuess (package:test/src/utils.dart:59:24)
        #10     currentOSGuess (package:test/src/utils.dart:59:7)
        #11     _declarer.<anonymous closure> (package:test/test.dart:66:17)
        <asynchronous suspension>
        #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
        #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
        #14     _ScheduleImmediateHelper._handleMutation (dart:html:53852)", source: http://localhost:60720/browser/generated_runner.dart.temp.html (1)

**Comment by travissanderson-wf** [comment]
based on https://github.com/dart-lang/test/pull/780 maybe test should release a patch to fix those of us still in Dart 1 land and then test could go to 0.13.0 (or 1.0.0!? 👍) and require Dart 2?

**Comment by nex3** [comment]
The intention here wasn't to drop support for Dart 1—I just didn't realize that `dart:io` stubbing wasn't supported there. I'll back out that change and release a patch.

**Comment by travissanderson-wf** [comment]
sounds good, thanks!
