### ISSUE TITLE
Running test fails when using build_runner and '-r json'

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/test#931]
Setup Dart 2.0.0, Ubuntu 18.04. This can be reproduce with the 'Dart Package' stagehand template after adding build_runner and build_test dependencies.

Running the simple test using

```
pub run test
pub run test -r json
pub run build_runner test
```

works fine however using:

```
pub run build_runner test -- -r json
```
fails with the following log:

```
[INFO] Generating build script completed, took 383ms
[INFO] Reading cached asset graph completed, took 79ms
[INFO] Checking for updates since last build completed, took 319ms
[INFO] Running build completed, took 14ms
[INFO] Caching finalized dependency graph completed, took 42ms
[INFO] Creating merged output dir `/tmp/build_runner_testTLHUMM/` completed, took 194ms
[INFO] Writing asset manifest completed, took 5ms
[INFO] Succeeded after 269ms with 0 outputs (0 actions)
Running tests...

{"protocolVersion":"0.1.1","runnerVersion":"1.3.1","pid":5519,"type":"start","time":0}
{"suite":{"id":0,"platform":"vm","path":"test/pbr_test_exp_test.dart"},"type":"suite","time":0}
{"test":{"id":1,"name":"loading test/pbr_test_exp_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1}
{"count":1,"type":"allSuites","time":3}
{"group":{"id":2,"suiteID":0,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":1175}
Unhandled exception:
Unsupported operation: Cannot extract a file path from a dart URI
#0      _SimpleUri.toFilePath (dart:core/uri.dart:4578:7)
#1      JsonReporter._addFrameInfo.<anonymous closure> (package:test/src/runner/reporter/json.dart:300:30)
#2      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:142:15)
#3      JsonReporter._addFrameInfo (package:test/src/runner/reporter/json.dart:299:42)
#4      JsonReporter._idsForGroups.<anonymous closure> (package:test/src/runner/reporter/json.dart:215:18)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#6      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#7      JsonReporter._idsForGroups (package:test/src/runner/reporter/json.dart:231:8)
#8      JsonReporter._onTestStarted (package:test/src/runner/reporter/json.dart:122:11)
```

**Comment by jakemac53** [comment]
It looks like this only happens with ddc, we end up with frames whos uri are dart:_internal etc, or package:somepackage, when we don't in dart2js. I can just skip them, but I don't understand where they are really coming from so going to do some more digging.
