### ISSUE TITLE
--reporter json throws exception on Windows

### ISSUE THREAD

**Issue by rspilker** [dart-lang/test#938]
Since using SDK 2.0, if I run the tests from WebStorm or the command line, I get an `UnsupportedOperation: Cannot extract a file path from a dart URI` exception.

test version 1.3.2

On the same computer, if I run the same command from a mingw64, everything works as expected.

I cannot run any tests from WebStorm.

```shell
D:\webstormprojects\dart-html-whitelist>pub run test -r json D:/webstormprojects/dart-html-whitelist
{"protocolVersion":"0.1.1","runnerVersion":"1.3.2","pid":15280,"type":"start","time":0}
{"suite":{"id":0,"platform":"vm","path":"D:/webstormprojects/dart-html-whitelist\\test\\collector_test.dart"},"type":"suite","time":6}
{"test":{"id":1,"name":"loading D:/webstormprojects/dart-html-whitelist\\test\\collector_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":8}
{"suite":{"id":2,"platform":"vm","path":"D:/webstormprojects/dart-html-whitelist\\test\\uris_test.dart"},"type":"suite","time":33}
{"test":{"id":3,"name":"loading D:/webstormprojects/dart-html-whitelist\\test\\uris_test.dart","suiteID":2,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":33}
{"suite":{"id":4,"platform":"vm","path":"D:/webstormprojects/dart-html-whitelist\\test\\whitelist_test.dart"},"type":"suite","time":38}
{"test":{"id":5,"name":"loading D:/webstormprojects/dart-html-whitelist\\test\\whitelist_test.dart","suiteID":4,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":38}
{"count":3,"type":"allSuites","time":39}
{"group":{"id":6,"suiteID":0,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":31,"line":null,"column":null,"url":null},"type":"group","time":5152}
Unhandled exception:
Unsupported operation: Cannot extract a file path from a dart URI
#0      _SimpleUri.toFilePath (dart:core/uri.dart:4578:7)
#1      JsonReporter._addFrameInfo.<anonymous closure> (package:test/src/runner/reporter/json.dart:300:30)
#2      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:142:15)
#3      JsonReporter._addFrameInfo (package:test/src/runner/reporter/json.dart:299:42)
#4      JsonReporter._idsForGroups.<anonymous closure> (package:test/src/runner/reporter/json.dart:215:18)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#6      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#7      JsonReporter._idsForGroups (package:test/src/runner/reporter/json.dart:231:8)
#8      JsonReporter._onTestStarted (package:test/src/runner/reporter/json.dart:122:11)
#9      _rootRunUnary (dart:async/zone.dart:1136:13)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#14     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379:20)
#15     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254:5)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#21     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379:20)
#22     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254:5)
#23     LiveSuiteController.reportLiveTest (package:test/src/runner/live_suite_controller.dart:136:30)
#24     Engine._runLiveTest (package:test/src/runner/engine.dart:367:21)
<asynchronous suspension>
#25     Engine._runGroup (package:test/src/runner/engine.dart:320:19)
<asynchronous suspension>
#26     Engine._runGroup (package:test/src/runner/engine.dart:315:19)
<asynchronous suspension>
#27     Engine._runGroup (package:test/src/runner/engine.dart:315:19)
<asynchronous suspension>
#28     Engine.run.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/runner/engine.dart:274:17)
<asynchronous suspension>
#29     new Future.sync (dart:async/future.dart:224:31)
#30     Pool.withResource.<anonymous closure> (package:pool/pool.dart:126:18)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#37     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

**Comment by rspilker** [comment]
Fixed in 1.3.3.

It was introduced in a28ee4a297f9bfc8151e16468c3bce3c35fdd18c and fixed in 642c823addb2185294d33e0d7d05ba6bb5d6a78d
